nodes:
  - id: 1
    eds_file: config/V02.06.02.00.eds
    device_family: "Varta"
    topic: "battery_varta"
    frame_id: "battery_varta"
    publish:
      - '26752:0'
      - '6656:1'
      - '6664:2'
    subscribe: []
