battery_bus:
  device: can_peak
  driver_plugin: can::SocketCANInterface
  master_allocator: canopen::SimpleMaster::Allocator
battery_sync:
  interval_ms: 100
  overflow: 2

battery_nodes:
  varta_battery:
    id: 1
    eds_file: /home/robotics/SASs_AMR_ws/src/battery_varta/battery_varta/config/battery_varta.eds
    device_family: Varta
    topic: battery_varta
